#ifndef RAINLANG_TOKENTYPE_H
#define RAINLANG_TOKENTYPE_H

enum TokenType {
    // Single char token types
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, STAR, SLASH, PERCENT, SEMICOLON, AT,

    // One or two char tokens
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, LOGICAL_AND, LOGICAL_OR,

    // Types
    STRING, CHAR, DECIMAL, INT, BOOL,

    // Literals
    IDENTIFIER, STRING_LITERAL, CHAR_LITERAL, DECIMAL_LITERAL, INT_LITERAL,

    // Keywords
    NOPE, IF, ELSE, WHILE, FOR, RETURN, VAR, CONST, TRUE, FALSE, FN,

    eOF
};

#endif //RAINLANG_TOKENTYPE_H